# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: /

collections:
  projects:
    output: true

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap

title: Craig Duthie Portfolio
tagline: An avid gameplay and tools programmer
description: My programming portfolio including game devlopment and web development projects, both professional and personal.
twitter:
  username: craig_duthie
  card: summary

social:
  name: Craig Duthie
  links:
    - https://twitter.com/craig_duthie
    - https://www.linkedin.com/in/craig-duthie-7b728b70/
    - https://github.com/cd1232

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:  
  - "*.config.js"
  - "package*.json"
  - "assets"
  - "node_modules"
